version: '3.2'

# Define services
services:
  # App backend service
  app-server_ex:
    # Configuration for building the docker image for the backend service
    image: docker.pkg.github.com/brunosbastos/exdelivery/backend:latest  
    ports:
      - "8080:8081"
    restart: always
    depends_on:
      - db_ex # This service depends on mysql. Start that first.
    environment: # Pass environment variables to the service
      SPRING_DATASOURCE_URL: jdbc:mysql://db_ex:3307/exdelivery
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin_pass
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend

  app-client_ex:
    
    image: docker.pkg.github.com/brunosbastos/exdelivery/frontend:latest
    ports:
      - "3000:3001"
    restart: always
    depends_on:
      - app-server_ex
    networks:
      - frontend

  # Database Service (Mysql)
  db_ex:
    image: mysql:5.7
    ports:
      - "3306:3307"
    restart: always
    environment:
      MYSQL_DATABASE: exdelivery
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin_pass
      MYSQL_ROOT_PASSWORD: 0x1c0e6ae
    volumes:
      - db_ex-data:/var/lib/mysql
    networks:
      - backend

# Volumes
volumes:
  db_ex-data:

# Networks to be created to facilitate communication between containers
networks:
  backend:
  frontend:
